apiVersion: v1
kind: Pod
metadata:
  name: health
  labels:
    app: health
spec:
  containers:
    - image: hashicorp/http-echo:1.0
      name: registry
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
