apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  template:
    metadata:
      name: nginx
      labels:
        tier: backend
    spec:
      containers:
        - image: nginx:1.23.4
          name: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: backend
